# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!
pod 'Firebase', '>= 2.5.0'
pod 'TwilioSDK', '~>1.2'
pod 'AFNetworking', '~> 2.0'


target 'hacktechtests' do

end



